### ISSUE TITLE
Export fails on Windows

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3743] opened 2016-02-23 19:13 UTC
Create new doc (ctrl+n)
drag out an ellipse
apply a drop shadow to it
click export icon on title bar 
click export, nav to desired folder, click ok
Export dialog remains open, note "1x" is now red

Result: 
`Export Failed for asset 0 of layerID 3, documentID 468, with error:  Failed to export components: Error generating component: undefinedError: Failed to export components: Error generating component: undefined`

**Comment by mcilroyc** [comment] 2016-02-25 16:18
so far, CNR

**Comment by chadrolfs** [comment] 2016-02-25 17:42
:cry: still repro’s with current master and build 1099 (also tried on a completely different machine and repro'd this bug)

**Comment by tommcrae** [comment] 2016-02-25 20:22
I had success with build 1098 on Windows 10 SP4 (Surface Pro 4).

However, the STR say:
_export icon on title bar (opens Export dialog, note "1x" is red)
_I don't see "red". How/when does "red" appear?

**Comment by ktaki** [comment] 2016-02-26 00:36
Tom M and I tried to reproduce the issue. So far, we know:

CNR with Tom M's SP4 and Cory's SP4. Repro'd with my SP3, my Dell desktop, and Chad's two systems. It looks like the Export As is broken for those machines since new AIDE and FLite were checked in (cl 1064031, 2/18).

**Comment by chadrolfs** [comment] 2016-02-26 01:24
Thanks to super sluething by @tommcrae and @mcilroyc, they figured out that the AIDE/FLITE stuff was probably built with VS 2015 which requires “Visual C++ Redistributable for Visual Studio 2015” to be installed on the machine for those to work.
https://www.microsoft.com/en-us/download/details.aspx?id=48145
 
After installing, we have success.

**Closed** 2016-02-27 00:13 UTC
Labels: Export, High Pri, Polish, Ship Blocker
