### ISSUE TITLE
On-canvas highlighting broken

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3251] opened 2015-11-16 19:54 UTC
create a new doc, select the artboard
Result: adders do not show on-canvas

create some rects and mouse over
result: no blue highlighting

**Comment by chadrolfs** [comment] 2015-11-16 21:01
Show Policy Frames doesn't work either

**Comment by volfied** [comment] 2015-11-24 21:00
Something changed and we no longer get OS.externalMouseMove events, I'm looking at it.

**Comment by volfied** [comment] 2015-11-24 21:00
https://github.com/adobe-photoshop/spaces-design/issues/3278 is a dupe of this.

**Comment by volfied** [comment] 2015-11-24 21:16
https://jira.corp.adobe.com/browse/PS-306

**Comment by chadrolfs** [comment] 2015-11-30 18:24
related to #3312

**Comment by shaoshing** [comment] 2015-11-30 23:44
Fixed by #3320

**Closed** 2015-12-01 21:06 UTC
Labels: Fixed but not closed, High Pri
