### ISSUE TITLE
Pen Tool: program error when creating multiple shapes with Pen Tool

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2107] opened 2015-08-19 20:49 UTC
1- file new
2 - create a closed path (triangle) with the Pen Tool
3 - Shift+click on the path to start a new shape
4 - click again to split the triangle (draw a line across the triangle)
5 - Select Shape 1 to not have Shape 2 selected
6 - Click on the document to start a new line

Program error dialog <OK> everything commences as usual

(I have a video if anyone wants)

**Comment by chadrolfs** [comment] 2015-08-19 20:56
this could be a dupe of #1681

**Closed** 2015-08-20 18:01 UTC
Labels: duplicate
