### ISSUE TITLE
Swap smart objects

### ISSUE THREAD

**Issue by colorage** [adobe-photoshop/spaces-design#1586] opened 2015-06-16 14:39 UTC
I can`t swap smart objects.

1. Select 2 smart objects.
2. Press "Swap" button.

**Comment by chadrolfs** [comment] 2015-06-16 20:42
@colorage thanks for reporting this.  I am unable to reproduce this issue.  Can you provide more details, a screenshot or the file you're using?  Anything special about your set-up?  Thank you!

**Comment by colorage** [comment] 2015-06-17 07:52
@chadrolfs after restarting Photoshop I can`t reproduce this bug.

**Comment by chadrolfs** [comment] 2015-06-17 15:26
@colorage thanks for the follow-up!  I'll close this as CNR (can not reproduce) but we can always re-open if we run into it again with solid repro steps.

**Closed by chadrolfs** 2015-06-17 15:26 UTC
