### ISSUE TITLE
Scrubbing position needs performance improvement (finesse) 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3424] opened 2015-12-10 22:58 UTC
Performance should mirror standard PS:
small drag mouse movements should increment/decrement by 1 value
Shift + drag should increment/decrement by 10

**Comment by chadrolfs** [comment] 2016-01-19 19:26
Should be in parity with standard PS functionality.  See scrubbing X and Y of an object in Free Transform mode.

**Comment by iwehrman** [comment] 2016-01-21 18:49
dupe of #3426

**Closed by iwehrman** 2016-01-21 18:49 UTC
Labels: Workflow
