### ISSUE TITLE
Setting W or H values to zero for text or graphics layers will make the fields to be blank and not editable

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#3711] opened 2016-02-16 23:55 UTC
As noted by @jsbache:

Problem: Setting W or H values to zero or less for text or graphics layers will make the fields to be blank and not editable.
Method: In Design Space, create a text layer, (or paste a graphic on to the canvas.) In the property panel, set Width (or Height) to 0 (zero).
Result: "0.1" flashes and leaves the fields, W, H, X, and Y to be blank.Those fields become inaccessible.
Expected: The minimum value 0.1 should be intact.
Workaround: Only undo will recover the layer contents.
Note: The case for graphics layer was previously reported as https://watsonexp.corp.adobe.com/#bug=4080692.

**Comment by iwehrman** [comment] 2016-02-17 02:14
I can repro the behavior, but strangely it seems that we _are_ correctly clamping values to a lower bound of 0.1. Maybe there should be a different minimum dimension length for text and graphics layers in particular? It works correctly at the moment for vector layers, e.g. @ktaki do you have any suggestions or guidance about how standard PS works here?

**Comment by ktaki** [comment] 2016-02-17 17:54
With standard Ps, entering out of bounds values will display a warning dialog and force the value to be minimum or maximum value allowed after dismissing the dialog. For a text layer, the minimum value allowed in standard Ps is 1 where DS enters 0.1. Could this be the problem? For a shape layer the minimum value in standard Ps is 0 where DS forces to be 0.1. This is fine.

Note: This is tracked down to the issue #3153 in which JIRA bug was opened as https://jira.corp.adobe.com/browse/PS-884.
@jsbache recommended to fix this in JS side and assigned the bug to Divya.
We could close this as a dupe of #3153.

**Comment by iwehrman** [comment] 2016-02-17 19:07
OK, yes, the discrepancy for type layers' minimum size between 0.1 and 1 is the problem. Do you know if this is the case for graphics layers as well?

**Comment by ktaki** [comment] 2016-02-17 19:23
Yes, 1 px is the minimum for the graphics layer in standard Ps.

**Comment by chadrolfs** [comment] 2016-02-17 21:57
I think this is a dupe of #3153

**Comment by iwehrman** [comment] 2016-02-17 22:08
Yes, closing this as a dupe of #3153. PR for that bug forthcoming.

**Closed by iwehrman** 2016-02-17 22:08 UTC
Labels: Duplicate, Question
