### ISSUE TITLE
Integrate layer comps from PS core

### ISSUE THREAD

**Issue by ajzeigert** [adobe-photoshop/spaces-design#3741] opened 2016-02-22 23:56 UTC
I understand that Design Space is supposed to be a lean and mean screen design app, so keeping it simple is key. But one of the pieces of core photoshop I find myself switching back for the most is Layer Comps. 

Many of the mockups I'm working on are derived from the same basic layout. Layer Comps allow me to keep duplicate artboards and elements to a minimum, creating only a few alternates for pieces of a composition. Layer Comps help keep file size down and prevent having to update several artboards when a "shared" element needs updated.

Maybe my workflow could use updated? Not sure how many others use Layer Comps for mockup work.

**Comment by chadrolfs** [comment] 2016-02-24 00:00
Hey, @ajzeigert thanks for the report!  We've moved this feature request to our [Wish List](https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist) page and are closing this because it's technically not a bug/defect.

**Closed by chadrolfs** 2016-02-24 00:00 UTC
Labels: Enhancement, Workflow
