### ISSUE TITLE
Change Width/Height will change X and Y instead

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2820] opened 2015-10-06 00:17 UTC
Reproduce: 

1 create a vector
2 deselect and then select the vector
3 use up/down arrow keys to change width or height
4 double click the vector
5 use up/down arrow keys to change width or height
6 go back to setp 2 

https://www.dropbox.com/s/1fe0jpo59xu0idj/rp-2.mov?dl=0

**Comment by chadrolfs** [comment] 2015-10-06 16:27
I think this is a dupe of #2776.

**Closed** 2015-10-06 17:42 UTC
Labels: duplicate
