### ISSUE TITLE
Export All error dev764

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2939] opened 2015-10-14 06:58 UTC
```
Export: Found configured port: 59596
export.js:881 Export: Generator plugin connection established
history.js:664 History state added or merged: 44
export.js:195 Export Failed for asset 0 of layerID 41, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}__stackCleaned__: truemessage: "Generator call exportLayer has timed out"stack: "Error: Generator call exportLayer has timed out↵    at file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/exportservice.js:148:23↵From previous event:↵    at ExportService.exportAsset (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/exportservice.js:147:19)↵    at Object._exportAsset (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/export.js:182:31)↵    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/export.js:747:49)↵    at file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1179:46↵    at List.__iterate (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:2756:13)↵    at IndexedIterable.mappedSequence.__iterateUncached (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1178:23)↵    at seqIterate (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:607:16)↵    at IndexedIterable.IndexedSeq.__iterate (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:321:14)↵    at IndexedIterable.mixin.toArray (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:4218:23)↵    at new List (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:2619:62)↵    at reify (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1729:37)↵    at List.mixin.map (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:4376:14)↵    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/export.js:746:26)↵    at file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1592:45↵    at file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1179:46↵    at file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1030:56↵    at List.__iterate (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:2756:13)↵    at ToIndexedSequence.__iterate (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1030:25)↵    at IndexedIterable.mappedSequence.__iterateUncached (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/bower_components/immutable/dist/immutable.js:1178:23)↵From previous event:↵    at Object.exportLayerAssets (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/actions/export.js:737:14)↵    at FluxController._applyAction (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:568:36)↵    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:662:37)↵From previous event:↵    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:658:22)↵    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:291:27)↵    at null.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:303:26)↵From previous event:↵    at AsyncDependencyQueue._processNext (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:299:21)↵    at AsyncDependencyQueue.push (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/util/async-dependency-queue.js:143:14)↵    at Object.<anonymous> (file:///Applications/photoshop-Release_x86_64/Plug-Ins/Spaces/www/src/js/fluxcontroller.js:641:42)↵    at React.createClass.mouseUpHandler (file://./js/jsx/tools/SuperselectOverlay.jsx:390:48)"__proto__: dexport.js:195 (anonymous function)bluebird.js:4559 tryCatcherbluebird.js:2687 Promise._settlePromiseFromHandlerbluebird.js:2761 Promise._settlePromiseAtbluebird.js:180 Async._drainQueuebluebird.js:185 Async._drainQueuesbluebird.js:67 Async.drainQueues
export.js:195 Export Failed for asset 0 of layerID 7, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 15, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 33, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 45, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 54, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 61, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 94, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 104, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 124, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 108, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 112, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 116, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 120, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
export.js:195 Export Failed for asset 0 of layerID 189, documentID 195, with error:  Error: Generator call exportLayer has timed out {stack: "Error: Generator call exportLayer has timed out↵  …e://./js/jsx/tools/SuperselectOverlay.jsx:390:48)", message: "Generator call exportLayer has timed out", __stackCleaned__: true}
history.js:664 History state added or merged: 45
history.js:664 History state added or merged: 46
history.js:664 History state added or merged: 47
```

**Comment by mcilroyc** [comment] 2015-10-14 14:15
I think this is a dupe of #2340  - but seth if you have any information about what kind of layer this was, that could be helpful

**Comment by placegraphichere** [comment] 2015-10-14 18:20
These were only artboards being exported using the Export modal. I created the file fully within Ds. Shapes, placed images and text layers. Lemme know if you need access to the file.

**Comment by ktaki** [comment] 2015-10-15 19:06
@placegraphichere Can you post your file to somewhere I can reach? Thanks.

**Comment by chadrolfs** [comment] 2015-10-16 18:05
@ktaki if you think this is a dupe of #2340, can you close?  If not, please remove the dupe label.

**Comment by ktaki** [comment] 2015-10-16 18:17
@placegraphichere I am closing this as a dupe of #2340, but still, if you can send or post the file caused this error, I will test it when the issue is fixed.

**Closed by ktaki** 2015-10-16 18:17 UTC
Labels: duplicate, High Pri
