### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2031] opened 2015-08-13 22:12 UTC
Open a large file in PS (~150MB) and jump to DS (with the 2-panels open) - takes ~ 4 seconds to draw the UI in the panels. Can we speed this up (jumping to/from PS to DS).

**Comment by iwehrman** [comment] 2015-08-13 22:19
This is a duplicate of #790. Thus, closing this as a duplicate.

**Closed by iwehrman** 2015-08-13 22:19 UTC
