### ISSUE TITLE
Panning on canvas disconnects superselect overlay from layers

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#3303] opened 2015-11-24 23:58 UTC
If you select the superselect tool and while hovering over layers you pan the canvas you can easily create a state where you see things like 
![screen shot 2015-11-24 at 3 48 41 pm](https://cloud.githubusercontent.com/assets/1008531/11384380/12e92460-92c4-11e5-8481-728b7485bc57.png)

**Comment by pineapplespatula** [comment] 2015-11-25 00:05
@volfied I'm having trouble reproducing this consistently since it seems like there are other issues with overlays in master.

**Comment by volfied** [comment] 2015-11-25 16:17
Highlighting does not work currently due to us not receiving `OS.externalMouseMove` events. However, you can confirm that UI updates w.r.t panning by turning on Policy Frames in Help menu. 

Can you confirm that in master, with Help>Show Policy Frames the policies don't update as you pan?

**Comment by pineapplespatula** [comment] 2015-11-25 16:55
border policies update correctly on drag in master

**Comment by chadrolfs** [comment] 2015-11-30 18:39
related or dupe of #2754?

**Comment by iwehrman** [comment] 2016-01-21 19:16
This is CNR for me. Can you verify @chadrolfs?

**Comment by ktaki** [comment] 2016-01-22 22:17
There is a good chance you can reproduce a separation of the policy frame.

Open a new artboard doc. Select the artboard. Option-drag it to make copies of the artboard several times continuously and quickly. (You might be able to do it with option-dragging groups.)

![screen shot 2016-01-22 at 8 56 52 am](https://cloud.githubusercontent.com/assets/2029597/12524577/b69b7410-c112-11e5-8e84-30566d99bff4.png)

**Comment by chadrolfs** [comment] 2016-01-22 23:01
@ktaki I CNR on both Mac and Win.  Can you try and let me know if you can still repro?

**Comment by ktaki** [comment] 2016-01-23 00:28
CNR with mac build 997. I will keep this open and come back later.

**Comment by ktaki** [comment] 2016-01-23 00:46
Oh, well. I just got it. This time, Moving "Artboard 1 copy" using superselect tool, and manipulated W H X Y by scrubbing.

![screen shot 2016-01-22 at 4 41 37 pm](https://cloud.githubusercontent.com/assets/2029597/12526887/7e56048e-c127-11e5-92b5-6ce14ff76ea9.png)

**Comment by ktaki** [comment] 2016-01-26 00:32
I reproduced once more today. I think this is definitely reproducible. Scrubby issue might be related to the  issue #3591. Try using scrubby to change W and H, and then, drag and move the artboard.

**Comment by chadrolfs** [comment] 2016-02-19 21:43
Coordinate separation seen if you undo (see #3726 )

**Comment by iwehrman** [comment] 2016-02-20 01:20
@ktaki @chadrolfs I think this bug was originally about panning the canvas. Can you still repro by panning? I can't, at the moment.

If you have to move a layer to repro, do you think that would be a dupe of #2714?

**Comment by chadrolfs** [comment] 2016-02-23 00:54
CNR on both Mac and Win (dragging or panning).

**Comment by iwehrman** [comment] 2016-03-04 15:37
CNR for me too, so I'm closing. I think any other bugs related to bounds disconnection are already tracked, but if not please re-open!

**Closed by iwehrman** 2016-03-04 15:37 UTC
Labels: High Pri, Polish, Ship Blocker
