### ISSUE TITLE
Color picker returns focus to PS before closing

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2552] opened 2015-09-21 22:04 UTC
1. Enter a modal type state
2. Open the color picker
3. Edit one of the input (i.e., acquire focus)
4. Enter twice to commit the change and then blur the input (i.e., release focus to PS)
5. Press escape to dismiss the picker.

Result: The picker remains open and the modal type state is committed. 

Expected (I think): The picker is dismissed and the modal type state remains active.

**Comment by chadrolfs** [comment] 2015-09-24 20:19
find the dupe.

**Comment by chadrolfs** [comment] 2015-09-24 23:45
Dupe of #2417?

**Comment by ktaki** [comment] 2015-09-29 23:23
Currently closing Color Picker in any way commits text editing. This needs to be fixed. I want to continue typing after changing color.

**Comment by chadrolfs** [comment] 2015-10-13 23:00
This is fixed, closing.  The other issue @ktaki is referring to above, regarding focus, is tracked in another bug.

**Closed by chadrolfs** 2015-10-13 23:00 UTC
Labels: Medium Pri
