### ISSUE TITLE
El Capitan 10.11 Performance Issues

### ISSUE THREAD

**Issue by ChrisChiera** [adobe-photoshop/spaces-design#1585] opened 2015-06-16 13:38 UTC
Currently when using in El Capitan OS X 10.11 (15A178w) on a 5K iMace with 32GB ram, the beach ball constantly appears and momentarily freezes almost every 4 or so seconds as you attempt to perform any action.

**Comment by jsbache** [comment] 2015-06-16 14:12
Thanks for the report.
We have just started looking at OSX 10.11. You may also notice a redraw artifact around the application frame when you toggle in and out of Design Space.

**Comment by chadrolfs** [comment] 2015-06-19 21:04
https://watsonexp.corp.adobe.com/#bug=4010180

**Comment by iwehrman** [comment] 2015-06-23 18:00
A friendly twitter user also reports that Smart Guide labels and tooltips aren't showing on El Capitan:https://twitter.com/bbaiIey/status/613380410521718784

**Comment by baiIey** [comment] 2015-06-23 18:03
Thanks @iwehrman. This is what I'm seeing in PS CC (2015) on OS X El Capitan 10.11 beta 2. 

Feel free to let me know if you have any questions or comments.
![ps-el-capitan-guides](https://cloud.githubusercontent.com/assets/701984/8313403/4e2801c8-1997-11e5-8fba-c9f1d0cd9a55.gif)

**Comment by wuyue1990** [comment] 2015-07-24 00:53
same issue here. should be caused by the new font.

**Comment by tiburbage** [comment] 2015-08-14 01:04
FYI I have closed the Watson bug https://watsonexp.corp.adobe.com//#bug=4010180 based on the description of the problem reported in the Watson bug report, and the hardware/OS context. I was able to test our current builds on an iMac 5K with the 10.11 Beta 6 build and was using Design Space fully maximized and with our VermilionArtboards.psd test doc. The user experience was not significantly different from that with current builds on a MacBook Pro running 10.10 or 10.11 Beta 6. We will continue to test with Beta 6 and subsequent pre-release builds looking for deltas between 10.10 and10.11 of course.

**Comment by tiburbage** [comment] 2015-09-23 23:52
I'm closing this based on our experience in testing the last Beta builds (see Aug 13 comment). We should log specific performance issues with the GM OS release if found (should be available very shortly)

**Closed by tiburbage** 2015-09-23 23:52 UTC
Labels: High Pri, PS core, PS core hasWatson
