### ISSUE TITLE
Incorrect spaces-adapter version dependency on master

### ISSUE THREAD

**Issue by timuric** [adobe-photoshop/spaces-design#2002] opened 2015-08-12 16:15 UTC
After successful ``npm install`` and ``bower install `` I get following by running ``gulp compile`` :
```
Running "requirejs:de" (requirejs) task
Error: ENOENT, no such file or directory '/Applications/Adobe Photoshop CC 2015/Plug-ins/Spaces/www/src/../bower_components/spaces-adapter/src/lib/vectorMask.js'
In module tree:
    js/main
      js/fluxcontroller
        js/actions/index
          js/actions/documents
            js/actions/history
              js/actions/layers

{ [Error: Error: ENOENT, no such file or directory '/Applications/Adobe Photoshop CC 2015/Plug-ins/Spaces/www/src/../bower_components/spaces-adapter/src/lib/vectorMask.js'
In module tree:
    js/main
      js/fluxcontroller
        js/actions/index
          js/actions/documents
            js/actions/history
              js/actions/layers

    at Error (native)
]
  originalError: 
   { [Error: ENOENT, no such file or directory '/Applications/Adobe Photoshop CC 2015/Plug-ins/Spaces/www/src/../bower_components/spaces-adapter/src/lib/vectorMask.js']
     errno: -2,
     code: 'ENOENT',
     path: '/Applications/Adobe Photoshop CC 2015/Plug-ins/Spaces/www/src/../bower_components/spaces-adapter/src/lib/vectorMask.js',
     syscall: 'open',
     fileName: '/Applications/Adobe Photoshop CC 2015/Plug-ins/Spaces/www/src/../bower_components/spaces-adapter/src/lib/vectorMask.js',
     moduleTree: 
      [ 'js/actions/layers',
        'js/actions/history',
        'js/actions/documents',
        'js/actions/index',
        'js/fluxcontroller',
        'js/main' ] } }
```

**Comment by iwehrman** [comment] 2015-08-12 18:14
Hi @timuric, thanks for filing this! The problem is that, on master, bower refers to an out-of-date version of the spaces-adapter dependency. A short-term workaround is to clone spaces-adapter separately and then use [`bower link`](http://bower.io/docs/api/#link) to wire it up into spaces-design. The correct fix, of course, is to ensure that the dependency version is correct on master. I'll leave this bug open, and rename it, to track that issue.

**Comment by iwehrman** [comment] 2015-12-21 16:09
@mcilroyc will correct me if I'm wrong, but I believe this is now fixed due to process changes around updating dependency versions.

**Closed by iwehrman** 2015-12-21 16:09 UTC
Labels: Build, Low Pri
