### ISSUE TITLE
Moving a layer off artboard and back on messes up X Y coordinates for the layer

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#2756] opened 2015-10-02 00:29 UTC
1. Create an artboard that starts at X = 0, Y = 0. Move the artboard to 100,0 by changing the X input to 100. 
2. Create a layer off of the artboard. 
3. Set the X and Y of that layer to 0, 0 with the W and H inputs. 
4. The final coordinates of the layer become -100, 0 

Same family of issues as: #2613, #2752, #2754 

![alt text](https://www.dropbox.com/s/hjchzmqx4sw3xw4/layerwrongcoor.gif?raw=1 "Layer has wrong coordinates")

**Comment by ktaki** [comment] 2015-10-02 16:44
I think this is as designed. Since the rectangle is moved on to the Artboard 1, the rectangle coordinates becomes based on the artborad origin.

**Comment by DivyaPrabhakar** [comment] 2015-10-02 16:46
@ktaki The layer is not taking into account the artboards new origin. The artboard moved to 100, 0 therefore shouldn't the layer, if set to 0,0, go to 100,0 now? Currently, I think it goes to the old coordinates when the artboard was at 0,0.

**Comment by ktaki** [comment] 2015-10-02 17:40
The origin is set to the position of the upper left corner of the first artboard created.If a shape is created in the positive coordinates, meaning towards right and below the origin, the origin does not change. It says there. When you set the X to 0 for the shape layer, it falls inside of the artboard, therefore, the origin is calcuated based on the artboard. (-100,0) is correct.

Try this. Move the artboard to the right by setting artboard's X to 500. Create a rectangle at the right side of the artboard and outside of the artboard. set the X of rect to 0. The rect moved to the left side of the artboard. You will see the X is set to 1024. This is because the canvas is expanded and the origin of the layers outside of the artboards is changed.

Now, I see a bug here. the coordinates of the artboard should not change. The coordinates of all artboards are based on the first artboard created. It should never change even after canvas is expanded. I will open an issue for this if not reported yet.

**Comment by ktaki** [comment] 2016-02-18 22:42
@chadrolfs I think this can be closed as "as designed". My last comments "Now, I see a bug here..." is also as designed. Do you agree?

**Comment by chadrolfs** [comment] 2016-02-19 21:12
I think there are still bugs here.

1. Create a new AB doc, select AB (X,Y are 0,0), set X to -100 hit enter.  Result: X is 268?!?!
![ab-coords1](https://cloud.githubusercontent.com/assets/8442631/13188991/b453f918-d709-11e5-92bf-af7742b5bf9e.gif)

2. Initial drag of layer from one AB to another has incorrect coordinates relative to it's new AB home, adjustments to X and Y are applied relative to it's previous AB position.
![ab-coords2](https://cloud.githubusercontent.com/assets/8442631/13189114/5e2e2bca-d70a-11e5-8318-dc534bf15856.gif)

**Comment by chadrolfs** [comment] 2016-02-19 21:14
In light of those issues, I'm questioning if this is still a workflow issue (especially the 2nd one above).

**Comment by pineapplespatula** [comment] 2016-02-23 18:39
@chadrolfs  can you make a new bug out of Initial drag bug above, and close out this one. also see JIRA PS-1414

**Comment by chadrolfs** [comment] 2016-02-24 00:45
#3748 logged for object coords issue.  the rest of this will be solved via feature work PS-1414

**Closed by chadrolfs** 2016-02-24 00:45 UTC
Labels: Artboards, Medium Pri, Polish, Question, Release Note
