### ISSUE TITLE
Error creating mask on group where first child layer is a shape

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3753] opened 2016-02-24 23:16 UTC
new doc, drag out a couple shapes, group them (cmd+g), hit M

`Action tools.changeVectorMaskMode failed: TypeError: Cannot read property 'top' of null`

**Comment by chadrolfs** [comment] 2016-02-24 23:17
Related to #3267 

![mask-errongroup](https://cloud.githubusercontent.com/assets/8442631/13304473/a86f7eac-db09-11e5-9277-8dec28c74140.gif)

**Comment by chadrolfs** [comment] 2016-02-24 23:18
![screen shot 2016-02-24 at 2 25 43 pm](https://cloud.githubusercontent.com/assets/8442631/13304519/e68b1fd4-db09-11e5-8e29-a43f1d157eb3.png)

**Comment by volfied** [comment] 2016-02-25 00:07
@pineapplespatula I've started work on this in `barkin/3753` where I fix this issue (with a simple bounds check). But there is a much bigger underlying issue (#3754).

Also, even with my fix, because applyEllipse itself switches tools to superselect, we never redraw our policy borders, so clicks will not go correctly.

I tried making sense of the mask code but I'm not familiar with it. You may know the reason why or figure out how we can fix this without adding yet another check to resetBorderPoliciesThrottled call conditions.

Passing it to you, @pineapplespatula.

**Comment by pineapplespatula** [comment] 2016-02-25 17:53
#3754 is the same issue,  there isn't a valid bounds on the group upon creation. I tested out your branch but i'm still seeing the same problem there. 

there is already a check for  `this.flux.store("tool").on("change", _borderPolicyChangeHandler);` so i'm not sure why the vector mask state changing doesn't cause the change since 

_handleVectorMaskModeChange in tools.store emits a change event. 

back to @volfied

**Comment by volfied** [comment] 2016-02-25 18:01
Please check out commit https://github.com/adobe-photoshop/spaces-design/commit/c8b2f31c778e2afb33e52d6cad8902f6330504de and try reproducing both bugs.

**Comment by volfied** [comment] 2016-02-29 20:34
@chadrolfs please test this with the newly merged PR #3760

**Closed** 2016-02-29 23:29 UTC
Labels: High Pri, Masks, Polish, Ship Blocker
