### ISSUE TITLE
Layer effects: Color picker is at wrong position 

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2796] opened 2015-10-05 16:35 UTC
![color-picker](https://cloud.githubusercontent.com/assets/118264/10286788/4de2d39c-6b44-11e5-89cc-1f8ffb3f3148.gif)

**Comment by shaoshing** [comment] 2015-10-05 16:37
only occurs for effects in the bottom section of the panel.

**Comment by chadrolfs** [comment] 2015-10-05 16:39
dupe of #2560

**Closed** 2015-10-06 17:43 UTC
Labels: duplicate
