### ISSUE TITLE
De-Select layers on canvas does not seem to work

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3196] opened 2015-11-04 06:42 UTC
Shift+click, CMD+click and Shift+CMD+click on a selected layer does not de-select it on canvas.

**Comment by volfied** [comment] 2015-11-04 17:17
Should be fixed by #3198

**Comment by volfied** [comment] 2015-11-04 17:17
Dupe of #3195

**Closed by volfied** 2015-11-04 17:17 UTC
