### ISSUE TITLE
Zoom % not maintained going from PS to DS

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2111] opened 2015-08-19 21:41 UTC
Have a file at 200% and jump to DS, zoom goes back to default of 50%

**Comment by iwehrman** [comment] 2015-08-19 21:44
Closing as a dupe of #1999. CC @shaoshing since he's assigned, and @jsbache, @designedbyscience and @placegraphichere since we talked about it earlier in the week.

**Closed by iwehrman** 2015-08-19 21:44 UTC
