### ISSUE TITLE
CC Lib: sync icon appears to be syncing indefinitely

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2271] opened 2015-08-28 23:23 UTC

**Comment by chadrolfs** [comment] 2015-09-09 16:53
Re-assigning to myself to take a look.  Shaoshing CNR

**Comment by chadrolfs** [comment] 2015-09-10 21:26
Yeah, still able to easily repro this.  pgdev 602 with master @ 2007fd2

**Comment by shaoshing** [comment] 2015-09-10 23:16
Hey @chadrolfs , can you show me the screenshot of the console output after your reproduce the issue? I wanted to know the sync status in your machine and compare with mine.

**Comment by chadrolfs** [comment] 2015-09-14 16:43
![screen shot 2015-09-14 at 9 43 12 am](https://cloud.githubusercontent.com/assets/8442631/9855731/1a5b6e10-5ac5-11e5-87d4-a643f404d471.png)

**Comment by shaoshing** [comment] 2015-09-14 20:29
Thanks for the screenshot. I think I know where the problem is. Fixing this now.

**Comment by mcilroyc** [comment] 2015-09-15 14:51
reverting auto-close.  assigning to @chadrolfs

**Closed** 2015-09-15 19:17 UTC
Labels: CC Libraries, Fixed but not closed, High Pri
