### ISSUE TITLE
Create Rect doesn't always work

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2224] opened 2015-08-26 16:05 UTC
Open up the explore mt. hood - edit file (on my transfer in sjshare)
select the BG layer in the Top Nav folder
create a rectangle

RESULT: nothing happens; if I randomly continue to try to draw out it occasionally will draw out a rect

video for this on my transfer as well ("CreateRect.mp4")

**Comment by chadrolfs** [comment] 2015-08-26 23:33
I CNR with current resources so maybe this is fixed. (using dev 523 w/master @ ffa24f9)

**Comment by iwehrman** [comment] 2015-08-27 00:37
I've seen this bug. I think it might be related to multiple monitors. I also had trouble reproducing it reliably, but at one point I couldn't make rectangles in the bottom or right side of the canvas only.

**Comment by chadrolfs** [comment] 2015-08-31 22:49
@tiburbage can you try to repro this.

**Comment by ktaki** [comment] 2015-08-31 23:42
eMailed Tom B if he could repro this.

**Comment by tiburbage** [comment] 2015-09-01 01:55
I tried without success to have the tool fail to create a Rectangle shape using the steps and content Zorana cited. I did notice that the first Rectangle I drew just above the BG layer had a BLACK fill, so it was "invisible" over the black BG layer but was clearly created in the Layers hierarchy. Changed the fill color and there it was...

**Comment by zoranagee** [comment] 2015-09-01 02:21
Yes I've had that happen as well and I did check for this. I'll try to reproduce as well.

Apologize for errors and brevity. Tapping tiny keys.

On Aug 31, 2015, at 18:55, tiburbage <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried without success to have the tool fail to create a Rectangle shape using the steps and content Zorana cited. I did notice that the first Rectangle I drew just above the BG layer had a BLACK fill, so it was "invisible" over the black BG layer but was clearly created in the Layers hierarchy. Changed the fill color and there it was...

-

**Comment by ktaki** [comment] 2015-09-18 22:38
Nobody seems to be able to reproduce this. @zoranagee Can you try it again and let me know.

**Comment by chadrolfs** [comment] 2015-09-18 22:54
I think this may be the same bug as #2192

**Comment by ktaki** [comment] 2015-10-05 17:56
Here are the steps to reproduce.

Create AB doc with Web (1920x1080) template. Save and close the file.
In Finder, select the file and enter Cmd+d six times to duplicate the file. 7 files in total.
Reset DS. Make sure the superselect tool is the current tool.
Select the seven files and drag them to the app window to open the files.
Select rectangle tool and try draw a rectangle on canvas
RESULT: Nothing drawn on canvas. If you start mouse down outside of canvas, you can draw shapes. This non-start-drawable region will not change by scrolling screen or zoom level changes.

It seems that the number of files required to reproduce this issue depends on the width of the document. If you use iPhone 6 template (750 x 1334), it takes 15 or more files instead of 7.

**Comment by mcilroyc** [comment] 2015-10-05 21:08
should be addressed by recently closed PR 2803, @ktaki

**Comment by ktaki** [comment] 2015-10-08 18:10
There are still some other cases where shapes and text cannot be created on canvas. They are reported and tracked in the issue #2831. Closing this issue.

**Closed by ktaki** 2015-10-08 18:10 UTC
Labels: Fixed but not closed, High Pri
