### ISSUE TITLE
Artboard coordinates don't update after undo or moving artboard after moving it's children

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2831] opened 2015-10-06 21:18 UTC
create a new doc
move the AB
cmd/ctrl + z

Result: coordinates are off

**Comment by chadrolfs** [comment] 2015-10-06 21:19
another way to get them separated is to drag assets into the AB, move them and then move the AB.

**Comment by ktaki** [comment] 2015-10-06 22:44
Another way is to add an artboard to the left or up.

**Comment by iwehrman** [comment] 2015-10-20 21:54
FBNC to @ktaki.

**Comment by ktaki** [comment] 2015-10-20 23:33
Works much better than before.

Over undoing will result in an error.

Create an artboard doc.
Move the artborad.
Undo
Undo

RESULT: Transfer from edit.undo to history.decrementHistory failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Select” is not currently available.

![screen shot 2015-10-20 at 4 30 46 pm](https://cloud.githubusercontent.com/assets/2029597/10623909/31ef1e7e-7748-11e5-892a-c704bc601776.png)

**Comment by ktaki** [comment] 2015-10-20 23:47
Creation of artboards towards top or left won't create frame policy issue anymore, but undoing it sometimes shows the issue.

![screen shot 2015-10-20 at 4 38 36 pm](https://cloud.githubusercontent.com/assets/2029597/10624101/39cd55aa-774a-11e5-88e0-84f16a9de423.png)

**Comment by mcilroyc** [comment] 2015-10-21 00:53
@ktaki regarding your last two comments:  

For the first one, I have found a bug with moving artboards IF it causes a canvas shift; FIP

I can not repro the second one where creating artboard + undo results in bounds issue.  If you can figure out the "sometimes" part of it... any clues appreciated.

**Comment by ktaki** [comment] 2015-10-21 04:11
One way to reproduce this is to create many artboards to the left or up, and undo one by one. For example, create 15 artboards to the left of the first artboard.

<img width="1173" alt="screen shot 2015-10-20 at 9 02 03 pm" src="https://cloud.githubusercontent.com/assets/2029597/10627451/712c1c42-776e-11e5-886f-153ef8f15580.png">

Then undo one by one. At some point, you will see something like:

<img width="1171" alt="screen shot 2015-10-20 at 9 03 09 pm" 
src="https://cloud.githubusercontent.com/assets/2029597/10627458/95a240ba-776e-11e5-8c80-b7ba4659172f.png">

With this, entire policy frames are shifted to left. Undo again will fix it, but repeating mode undos show the shifting of policy frames again.

<img width="1173" alt="screen shot 2015-10-20 at 9 03 44 pm" src="https://cloud.githubusercontent.com/assets/2029597/10627464/aaa7ee88-776e-11e5-8143-01415d20bfd2.png">

**Comment by mcilroyc** [comment] 2015-10-21 19:19
FYI @ktaki I found a minimal set of repro steps for the above issue, and have submitted PR 3067 to address it.

As you said, begin with a new document and start creating artboards to the left.  When you create AB No. 4 it shifts the canvas enough such that creating No 5 will NOT *need* to shift the canvas.  When undoing that fifth AB, there is not an accompanying canvas shift event which is why the bounds were not reset appropriately.  This PR forces bound recalculations due to canvas shifts to be properly stored in the history state.

**Comment by mcilroyc** [comment] 2015-10-21 20:15
Back to @ktaki  - both of your recent comments/scenarios should now be resolved.

**Comment by ktaki** [comment] 2015-10-21 20:56
@mcilroyc Yes, the issues have been resolved. One question. When the second artboard is created to the left of Artboard 1, why does the X of the Artboard 1 jumps to 1500? I would expect 1024 to be added to the X. Actually, if you move the Artboard 1, then set the X to be 0, and then add Artboard 2 to the left, then X of artboard 1 to be 1024.

**Comment by mcilroyc** [comment] 2015-10-21 21:04
I can not explain this behavior @ktaki.  I have to believe it is a core issue/feature though.  It could also have to do with the gutter we put between artboards... or the way in which we're calculating that.

**Comment by ktaki** [comment] 2015-10-21 21:10
OK. Thanks. Closing as fixed.

**Closed by ktaki** 2015-10-21 21:10 UTC
Labels: Artboards, Fixed but not closed, High Pri
