### ISSUE TITLE
Entering Vector Mask mode on a masked group countaining a shape object selects the path associated with the shape instead of the mask on the group

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3267] opened 2015-11-18 00:58 UTC
(to reduce later confusion, note that @pineapplespatula originally filed this from my account, and he's the best person to talk about about STR, etc.)

**Comment by pineapplespatula** [comment] 2016-01-21 19:45
I cannot reproduce this anymore, @chadrolfs would you mind seeing if you can repro it?

**Comment by chadrolfs** [comment] 2016-01-22 23:57
@iwehrman can you provide steps or a test file for this?  I'm confused about STR.  Currently you can't have a mask on a shape layer.

**Comment by pineapplespatula** [comment] 2016-01-23 01:01
You can have a mask on the group though. 

![screen shot 2016-01-22 at 5 06 56 pm](https://cloud.githubusercontent.com/assets/1008531/12527042/d34ef278-c129-11e5-8368-3ec54eef5bd9.png)

**Comment by pineapplespatula** [comment] 2016-01-23 01:02
![screen shot 2016-01-22 at 5 07 51 pm](https://cloud.githubusercontent.com/assets/1008531/12527049/e3e1408c-c129-11e5-9ba2-85b6e91f6dfe.png)

**Comment by chadrolfs** [comment] 2016-01-25 19:29
I can repro.
![mask-shapepath](https://cloud.githubusercontent.com/assets/8442631/12561813/d2492d7e-c356-11e5-9dab-6c5c27b14a70.gif)

**Comment by chadrolfs** [comment] 2016-02-18 19:13
This is very confusing and problematic if a user is trying to delete the mask.  Entering mask mode in this case and hitting delete will do nothing.  Bumping to High.

**Comment by pineapplespatula** [comment] 2016-02-18 19:49
i created Jira bug PS-1080

**Comment by chadrolfs** [comment] 2016-02-19 16:19
Thanks for filing the JIRA bug, however I'm concerned that JP won't see this bug because he is on a different molecule team with their unique JIRA dashboard that only shows tasks/bugs assigned to that team.  Could you reach out to him to see if 1) he's aware of it, 2) if he's planning on fixing it, and 3) what his rough timeline is (when will he get to it)?  Thanks.

**Comment by iwehrman** [comment] 2016-02-19 17:56
Alternatively, re-assign to @jsbache so that he can triage it when he returns.

**Comment by pineapplespatula** [comment] 2016-02-19 23:51
Talked to JP, he wont be able to get to it for a while I'm going to reassign this to @jsbache for now

**Comment by chadrolfs** [comment] 2016-02-20 00:12
:+1: thanks

**Comment by pineapplespatula** [comment] 2016-02-22 23:14
Looking into the photoshop call stack, i'm not as convinced that this is a core issue, somehow the sheet that is being affected is the shape and not the group. i do not yet understand why that is the case

**Comment by pineapplespatula** [comment] 2016-02-24 00:19
The root cause of this bug is that entering and exiting vector mask mode changes the layer selection
in the gif below i select the group layer. press M twice and switch to classic to observe the current layer selection . 

![mask_layer_issue](https://cloud.githubusercontent.com/assets/1008531/13271332/3447a18c-da49-11e5-8e8b-4c21221caec1.gif)

**Comment by pineapplespatula** [comment] 2016-02-24 00:45
I just submitted a fix to perforce for jira 1080. @chadrolfs can you take a look?

**Comment by chadrolfs** [comment] 2016-02-24 22:27
I get an error at the step attempting to apply a mask to a group that has it's first child as a shape
`Action tools.changeVectorMaskMode failed: TypeError: Cannot read property 'top' of null`

![screen shot 2016-02-24 at 2 25 43 pm](https://cloud.githubusercontent.com/assets/8442631/13303207/c39cf56c-db02-11e5-9f08-68505cb517ab.png)

**Comment by chadrolfs** [comment] 2016-02-24 23:57
Blocked by #3753 and #3754

**Comment by pineapplespatula** [comment] 2016-02-29 22:19
@chadrolfs , I think this should be unblocked.

**Closed** 2016-03-01 00:13 UTC
Labels: High Pri, Masks, Polish, PS core, PS core has bug, Ship Blocker
