### ISSUE TITLE
After placing an image onto a new Artboard, the placeholder 'Layer 1' still displays

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2599] opened 2015-09-23 21:32 UTC
After Place Linked or Place Embedded onto a new Artboard, the placeholder Layer 1 still displays (even though it really isn't there anymore).

1 - With the LAYERS panel visible, File > New (Artboard)
2 - File > Place Embedded [select an image] Place
3 - Press ENTER to complete

Note "Layer 1" still appears in the LAYERS list. If you switch back to standard, it really isn't there.

**Comment by tiburbage** [comment] 2015-09-23 21:34
Tested on Mac and Windows, playground / staging 2015/09/23

**Comment by chadrolfs** [comment] 2015-09-24 21:27
Happens in classic PS the same for all smart objects (Placed, Linked, Cloud).  Probably as designed.  If you think this needs to be fixed, please write up a Watson bug, otherwise go ahead and close this.

**Comment by iwehrman** [comment] 2015-09-24 21:29
I wonder if this is happening some times but not others... There has been confusion about this before. It's possible that the behavior changed in standard PS fairly recently?

**Comment by tiburbage** [comment] 2015-09-29 00:04
Just retesting around this today with our staging build on Mac (1607, 09/28).
In standard, if I create a new Artboard, then Place Embedded an image, the placeholder Layer 1 immediately disappears, replaced by the Embedded image layer. If I do the exact same steps in DS, "Layer 1" is still visible (the Artboard appears to have 2 layers). If I attempt to select that layer, the panel refreshes and it disappears.

**Comment by volfied** [comment] 2016-02-03 00:14
I believe this is fixed now. My guess is the problem was related to the fact that we were in a modal transform state when placing, which would cause the addLayer call to not complete correctly and replace the existing layer. But now that we don't go into a modal state and immediately place the image, everything works fine.

@chadrolfs please verify.

**Closed** 2016-02-03 23:58 UTC
Labels: Fixed but not closed, Medium Pri, Polish, PS core
