### ISSUE TITLE
Design Space: DS panel has no response after switch from Standard Photoshop to Design Preview workspace.

### ISSUE THREAD

**Issue by fzhu1978** [adobe-photoshop/spaces-design#2622] opened 2015-09-24 21:54 UTC
Watson bug: 4062280.
Problem: DS panel has no response after switch from Standard Photoshop to Design Preview workspace.  It blocks Design Space on French German Japanese build on windows.

Method:
1. Launch PS 20150918.m.231 build on DEU Win 8.1 64-bit OS.
2. Check "Enable Design Space" in preference dialog.
3. Open DS UI from Windows-> Workspace-> Design Space(Preview). 
4. DS worksapce display, it is in localized.
5. Check the response.

Result:
1. DS panel has no response after switch from Standard Photoshop to Design Preview workspace.
2. Welcome screen does not show.
3. Hover mouse to toolbar, loading and loading for long time.

Expected:
1. The top menu’s UI of DS panel is displayed correctly.
2. Welcome UI displayed.
3. The tool bar works well.

Note:  It's a Win only defect.

**Comment by volfied** [comment] 2015-09-24 21:59
@ktaki can you reproduce this and get us a console output?

**Comment by ktaki** [comment] 2015-09-24 22:45
Here it is.

![error_ds_japanese_win](https://cloud.githubusercontent.com/assets/2029597/10088911/30467a92-62d3-11e5-8327-dce39dd91572.png)

**Comment by ktaki** [comment] 2015-09-24 22:53
For Japanese, fixing MINIMIZE cleared the issue. Will check for French and German.

**Comment by volfied** [comment] 2015-09-24 22:59
Our check is for keyChar length, is this because the shortcuts in the other languages are unicode and we consider their lengths to be more than 1. @iwehrman any input?

**Comment by ktaki** [comment] 2015-09-24 23:04
German had an extra space before m as in " m" for MINIMIZE. Deleting the space cleared the issue. French did not have the issues.

**Comment by volfied** [comment] 2015-09-24 23:05
What issue did Japanese have? Was it space before the character as well?

**Comment by ktaki** [comment] 2015-09-24 23:07
Somehow the entry was made as "分" (minutes). Wrong translation. Since this is a keyboard shortcut (right?), no translation is necessary for the most of the cases.

**Comment by ktaki** [comment] 2015-09-24 23:12
One more thing. Why was this affected Windows only? I see the same translation on Mac, but Mac worked fine.

**Comment by volfied** [comment] 2015-09-24 23:20
Because we keep win and mac shortcuts in separate files. It looks like in DE and JA shortcuts those had a space before them.. @fzhu1978 can you please fix those translations? Shortcuts especially shouldn't be translated.

**Comment by iwehrman** [comment] 2015-09-24 23:23
@volfied It's perfectly fine to remove the single-character check. It was intended to be a sanity check, but I can see how that it may not be appropriate for languages with multi-byte characters.

**Comment by ktaki** [comment] 2015-09-24 23:26
Well, I think without the check, this error could not have been caught. Good to have the checking.

**Comment by fzhu1978** [comment] 2015-09-24 23:42
@volfied  I removed the translation resources for shortcuts, maybe it was changed before I move it. Let me check.

**Comment by fzhu1978** [comment] 2015-09-24 23:44
@volfied I see no space before shortcut character for de and ja.  Can you show me an example?

**Comment by volfied** [comment] 2015-09-24 23:51
https://github.com/adobe-photoshop/spaces-design/blob/master/src/nls/de/shortcuts-win.json#L51
https://github.com/adobe-photoshop/spaces-design/blob/master/src/nls/ja/shortcuts-win.json#L51

**Comment by ktaki** [comment] 2015-09-25 00:08
Note that " 分" should be corrected to "m".
@volfied We do not have Minimize menu item under Window, do we?

**Comment by fzhu1978** [comment] 2015-09-25 00:14
@voldied New pull request created: #2628.
I copied English shortcut file to F/G/J.  But, since shortcuts are not going to be translated, we don't process shortcuts files.  How can we get update with English shortcut files?

**Comment by volfied** [comment] 2015-09-25 00:35
@fzhu1978 We update the root files ourselves, best you can do is watch those files for changes in Github, and react to those changes.

**Comment by volfied** [comment] 2015-09-28 17:45
This is now fixed.

**Closed by volfied** 2015-09-28 17:45 UTC
Labels: High Pri
