### ISSUE TITLE
Artboards: Add new artboard using file menu

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#1905] opened 2015-08-04 19:44 UTC
Allow addition of a adding new artboard templates to canvas using the file menu.

**Layer > New Artboard > [options]**

We can grab the [options] from current Ps template options for artboards (I believe there are 10 or so).

![filemenu-layers](https://cloud.githubusercontent.com/assets/3229167/9048852/ffebe07a-3a01-11e5-914a-598138b609b8.png)

**Comment by chadrolfs** [comment] 2015-08-04 20:09
Basically duplicating File > New From Template, right?

**Comment by chadrolfs** [comment] 2015-08-04 20:10
Should this be a trello card?  This isn't really a bug/issue.

**Comment by DivyaPrabhakar** [comment] 2015-08-19 19:02
https://github.com/adobe-photoshop/spaces-design/pull/2063

- Added the menu specified above
- If no preset is defined and an artboard is selected, when new artboard is created, it takes the size of the selected artboard. Else, if no preset is defined and an artboard is not selected, the new one takes the default size.

**Comment by iwehrman** [comment] 2015-08-19 22:26
![ab](https://s3.amazonaws.com/f.cl.ly/items/2S2F293S0U1P3n3a3M45/Screen%20Recording%202015-08-19%20at%2003.25%20PM.gif)

**Comment by placegraphichere** [comment] 2015-08-19 22:32
this is radical and exciting

**Comment by DivyaPrabhakar** [comment] 2015-08-19 22:33
Wooooooooo

**Comment by iwehrman** [comment] 2015-08-19 22:34
@placegraphichere you have the power to close this bug once you are satisfied with the product.

**Comment by placegraphichere** [comment] 2015-08-24 21:32
I am coming across an issue where I add an artboard and it will often times freeze the UI completely. I am able to return to classic, but am not able to return to Ds. I'm on dev 507.

**Comment by placegraphichere** [comment] 2015-08-24 22:37
I've bower updated, npm updated, updated both my repos and pulled down dev 511 and still hit this issue on creation of a second artboard with the file menu

**Comment by DivyaPrabhakar** [comment] 2015-08-24 22:38
I can look into this in about an hour or so and see if I can find the problem/repro it

**Comment by DivyaPrabhakar** [comment] 2015-08-25 18:07
@placegraphichere I assigned this to myself because I have talked to Jesper about it and I think the problem is on our side, therefore I am going to try and isolate it. In the meantime, can you try to repro this problem but DO NOT deselect the new artboard after you have created it, just keep creating artboards. On my end, it is able to do this without problem.

**Comment by iwehrman** [comment] 2015-08-26 21:08
In the future, it would have been better to close this when the feature landed. The PR #2227 is really addressing a different issue entirely.

**Comment by iwehrman** [comment] 2015-08-26 22:47
I'm going to take the liberty of closing this even though it's assigned to @placegraphichere because it was implemented a while ago, and with #2227 it's now clearly bug free!

**Closed by iwehrman** 2015-08-26 22:47 UTC
Labels: Artboards, Fixed but not closed, Low Pri
