### ISSUE TITLE
Focus conflict: Arrow keys do not work on Type attributes in edit mode, Enter key erases selected type

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2252] opened 2015-08-27 23:13 UTC
click on canvas with Type tool and start typing, select all the text while still in edit mode, click in Size field and arrow up.

Result: size is unaffected and selection becomes blinking cursor

**Comment by chadrolfs** [comment] 2015-08-28 00:00
in edit mode, select type, click in color field and type "red" and hit Enter.
Result: carriage return in edit mode on canvas and color set to "black"

**Comment by chadrolfs** [comment] 2015-08-28 21:28
This is now on Mac as well with latest dev build 549

**Comment by iwehrman** [comment] 2015-08-30 16:29
Dupe of #1858?

**Comment by chadrolfs** [comment] 2015-08-31 17:18
Could be related but don't think it's a dupe as I read down through that issue.

**Comment by chadrolfs** [comment] 2015-08-31 19:34
This seems fixed now on Mac.  Still very broken on Win

**Comment by iwehrman** [comment] 2015-08-31 20:25
Can you articulate the difference between this and #1858?

**Comment by chadrolfs** [comment] 2015-08-31 20:54
Sure, as I understand it #1858: you enter a Text attribute field and you can't go back to editing the text on canvas because you haven't hit enter in the attribute field to apply it. Thus you have to hit enter twice.

This bug does almost the opposite, you enter a attribute field but keys are applied to on canvas rather than the attribute field.  For example, hitting tab you would expect it to move to the next attribute field but instead it inserts a tab into the on canvas text.

**Comment by iwehrman** [comment] 2015-08-31 21:17
OK, I understand now, thanks! I agree that it seems to work fine on Mac. I suspect this is a core issue and will ask @jfitz-adobe if he can repro.

**Comment by iwehrman** [comment] 2015-08-31 21:50
Blocked by [Watson 4046558](https://watsonexp.corp.adobe.com/#bug=4046558).

**Comment by iwehrman** [comment] 2015-09-01 17:14
FBNC to @chadrolfs as of whatever the Win equivalent of Mac pgdev.560 is from Tuesday morning.

**Closed** 2015-09-01 23:18 UTC
Labels: Fixed but not closed, High Pri, PS core, PS core hasWatson, Type, Windows Only
