### ISSUE TITLE
Unable to transform layer group if it has layer with missing font

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3319] opened 2015-11-30 20:39 UTC
Everytime when you try to grab the transform handles, the modal dialog shows up and interrupts your action. 

![missing-font](https://cloud.githubusercontent.com/assets/118264/11483772/29bcd052-975f-11e5-8ba9-2f41395ba0eb.gif)

**Comment by chadrolfs** [comment] 2015-11-30 21:10
dupe of #2686

**Closed** 2015-11-30 21:11 UTC
Labels: duplicate
