### ISSUE TITLE
Create New Artboard creates odd sized artboard when no artboard is selected

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2335] opened 2015-09-03 20:27 UTC
Open new artboard doc with iPhone 6 dimension.
Immediately, add a new artboard by Cmd+B. Note that Layer 1 is selected at this point.
RESULT: New artboard added has a dimension W1080 x H 1960. This dimension does not exist in the artboard presets. (This could be old default artboard dimension which no longer used.)
EXPECTED: Since no artboard was selected to duplicate the dimension, the dimension should be the same as the one last created.

**Comment by chadrolfs** [comment] 2015-09-11 22:18
I think this is a dupe of #2208

**Closed** 2015-09-11 23:27 UTC
Labels: duplicate
