### ISSUE TITLE
Dragging out guides from left (next to toolbar) occasionally fails

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2127] opened 2015-08-20 16:02 UTC
new doc
mouse over left side of work area next to toolbar until you see blue highlight, click and drag

result: no guide

**Comment by chadrolfs** [comment] 2015-08-20 18:14
probably caused by #2130

**Comment by volfied** [comment] 2015-08-26 20:16
Hoping this is a dupe of #2130, can you confirm Chad?

**Closed** 2015-08-26 22:18 UTC
Labels: Guides, Low Pri
