### ISSUE TITLE
Focus issue: Arrow keys change X/Y while W/H field has apparent focus

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2816] opened 2015-10-05 23:34 UTC
new doc
drag out a rect, switch to Select tool
click in W or H transform field, Shift + arrow up/down
click on canvas to deselect shape
click on shape to reselect
click in W or H transform field, Shift + arrow up/down
switch to rect tool and drag out a rect, switch to Select tool
click in W or H transform field, Shift + arrow up/down

Result: at some point within the steps above arrowing up/down moves the shape on canvas (X/Y).

**Comment by chadrolfs** [comment] 2015-10-05 23:34
https://www.dropbox.com/s/gwfmydw2q7feez8/XY-RefPointIssue.mov?dl=0

https://www.dropbox.com/s/2mhsbt95wgiegnr/XY-RefPointIssue2.mov?dl=0

**Comment by iwehrman** [comment] 2015-10-05 23:58
I think this is a dupe of #2776. X/Y are changing because the layer is moving up/down.

**Closed** 2015-10-06 16:28 UTC
Labels: duplicate, High Pri
