### ISSUE TITLE
Performance (perception): Document center jumps when opening file

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2184] opened 2015-08-24 18:07 UTC
1 - start in the null doc space
2 - open a file

Notice that initially it opens to a certain position and then depending on what panels you have open, the file jumps to a different position. This happens regardless if I have 1 column or 2 column as the default state. File always jumps a little. Adds to the clunkiness feel upon first launch.

(animated gif of this experience)
![documentshift](https://cloud.githubusercontent.com/assets/7904855/9448201/3a02e73c-4a50-11e5-8897-65cfed5f2741.gif)

(animated gif of this experience with 1 column as default - less severe but why does it still need to shift?)
![docshift_subtle](https://cloud.githubusercontent.com/assets/7904855/9448327/e0cb4b90-4a50-11e5-8b66-8417b4530f48.gif)

**Comment by iwehrman** [comment] 2015-08-24 18:40
I think this is a dupe of #1999. @shaoshing and @jsbache and I are going to discuss this and related issues tomorrow.

**Comment by iwehrman** [comment] 2015-09-25 19:34
Fixed by #2343.

**Closed by iwehrman** 2015-09-25 19:34 UTC
Labels: Medium Pri
