### ISSUE TITLE
How to activate Design Space on a french version Photoshop CC 2015 ?

### ISSUE THREAD

**Issue by Colir** [adobe-photoshop/spaces-design#1620] opened 2015-06-19 08:43 UTC
Hello,
i can't active Design Space on my version of Photoshop CC 2015 (French language)
The checkbox to enable it is unable (greyed)....

No matter that this is only in english, i just want to try it !!

i'm on win 8.1 64bit 

thanks

**Comment by iwehrman** [comment] 2015-06-19 14:23
As a technology preview, Design Space is not yet localized to languages other than English. And, more importantly, for legal reasons we had to ship with support disabled in France. You can work around this, though, by installing a different language pack, as described here: https://github.com/adobe-photoshop/spaces-design/wiki/Getting-Design-Space-running-in-French

Hope this helps! Closing this issue because it's known and (for better or for worse) as intended. Once you get it up and running, don't hesitate to file more issues here!

**Closed by iwehrman** 2015-06-19 14:23 UTC
