### ISSUE TITLE
Add even spacing align (distribute space) like Illustrator

### ISSUE THREAD

**Issue by jardicc** [adobe-photoshop/spaces-design#3481] opened 2016-01-08 18:34 UTC
http://feedback.photoshop.com/photoshop_family/topics/even_spacing_align_like_illustrator

Spacing out objects evenly no matter the object's width. IE: putting 20px between each differently shaped nav item.

**Comment by chadrolfs** [comment] 2016-03-02 22:23
Moving this to [Wishlist](https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist) and closing as not a bug/defect.

**Closed by chadrolfs** 2016-03-02 22:23 UTC
Labels: Enhancement, Workflow
