### ISSUE TITLE
Attempts to open color picker other openDialog sometimes fail

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1795] opened 2015-07-22 16:27 UTC
Open a file, select 2 layers, add inner then drop shadow, click on drop shadow color picker
Result: `Action dialog.openDialog failed: TypeError: Cannot read property 'getBoundingClientRect' of null`

**Comment by chadrolfs** [comment] 2015-07-22 16:29
this may need better repro steps and having the color picker partially obscured may be a part of it.  I ran into this with the blend mode drop down earlier this week but wasn't able to repro.  I may require trying this a couple times on different documents in the same session.

**Comment by chadrolfs** [comment] 2015-07-22 16:30
![screen shot 2015-07-22 at 9 32 35 am](https://cloud.githubusercontent.com/assets/8442631/8830983/3c6f6718-3054-11e5-9daa-68d0f955a9fb.png)

**Comment by chadrolfs** [comment] 2015-07-22 16:30
![screen shot 2015-07-22 at 9 25 15 am](https://cloud.githubusercontent.com/assets/8442631/8830994/43e7ec68-3054-11e5-96fb-754b73b72bbf.png)

**Comment by volfied** [comment] 2015-07-22 16:38
This is a dupe of https://github.com/adobe-photoshop/spaces-design/issues/1738

offsetParent of this.state.target is not always defined.

**Closed** 2015-07-22 18:05 UTC
Labels: duplicate, High Pri
