### ISSUE TITLE
X and Y coordinates are incorrect after moving artboard on the canvas

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#2754] opened 2015-10-02 00:14 UTC
1. Create new artboard, X and Y coordinates are at 0, 0 
2. enter "850" into the width input to position the artboard at 850,0 
3. The X value changes to "100"

![alt text](https://www.dropbox.com/s/20qtka7cvqxw51d/artboardwrongcoor.gif?raw=1 "Wrong coordinates")

Same family of issues as: #2613 and #2752

**Comment by chadrolfs** [comment] 2015-10-02 02:10
Possibly related to #2713 as well

**Comment by iwehrman** [comment] 2015-10-06 00:04
I'm kicking this, and any other bug that has to do with X/Y coordinates in infinite canvas mode, out of M3. The correct behavior is entirely unclear, and even if it were clear I think the risk of changing this code is too high given our proximity to the release.

**Comment by mcilroyc** [comment] 2015-10-19 15:57
Just confirming what Ian said while I'm addressing related bugs: the behavior described here is at least acting consistently and our model/bounds/UI seem to be in sync with PS.  In other words, I agree this is deferrable.

**Comment by volfied** [comment] 2015-12-07 22:10
I'd go even further and say that this is not a bug. We work with infinite canvas, and if you push the only leftmost artboard far enough right, PS will save on canvas space and remove some area from the canvas.

If our models are in sync with what PS is providing, and no bad behavior is being formed out of this, I suggest we close this.

**Comment by ktaki** [comment] 2016-02-18 22:36
@chadrolfs: I vote for closing this as "as designed". How do you think?

**Comment by chadrolfs** [comment] 2016-02-19 22:01
I agree.  Infinite canvas will shrink or grow depending on where you move things.  It's confusing but working correctly.

**Closed by chadrolfs** 2016-02-19 22:01 UTC
Labels: Artboards, High Pri, Release Note, Workflow
