### ISSUE TITLE
Type: setting attributes in initial edit mode leaves you in a state where you can't commit text (via Esc/Enter), Focus issue

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2313] opened 2015-09-02 16:12 UTC
new doc
(t) for type tool, click on canvas and type multiple lines
select all the text
click in color picker field, type "red"
tab to size and Shift + up arrow to increase size
select half of the text
click in color picker field, type "purple"
click in Typeface and change type
hit enter, hit Esc

Result: you are stuck in edit mode until you change tools

**Comment by chadrolfs** [comment] 2015-09-02 16:12
https://www.dropbox.com/s/eolsuvuaqmwl5ct/Type-cannot-commit.mov?dl=0

**Comment by iwehrman** [comment] 2015-09-03 14:26
I think this is a dupe of (or at least has the same root cause as) #1858.

**Comment by ktaki** [comment] 2015-09-04 16:55
The issue is when typeface is changed, the focus is not coming back to on canvas to continue editing. (as I reported in #2337). Color changing part is working as expected.

**Comment by ktaki** [comment] 2015-09-08 18:13
https://watsonexp.corp.adobe.com/#bug=4051807

**Comment by chadrolfs** [comment] 2015-09-11 18:18
Might be fixed now with latest fix from Fitz

**Comment by ktaki** [comment] 2015-09-11 18:27
With John F's fix and current master, when trying to change font in editing mode, you get:

![screen shot 2015-09-11 at 11 25 38 am](https://cloud.githubusercontent.com/assets/2029597/9822914/0cee3996-5878-11e5-8913-63bac693c837.png)

**Comment by chadrolfs** [comment] 2015-09-11 22:41
yeah, not fixed yet

**Comment by ktaki** [comment] 2015-09-14 14:48
Fixed on Mac, but still not working on Windows.

**Comment by ktaki** [comment] 2015-09-14 16:37
Updated the watson bug with a comment:
Fixed on Mac. Still has issues with Windows. When font is changed in text editing mode, you cannot continue typing even though you see I beam cursor on canvas. The situation has improved, however. Now you can click on the type layer on canvas to recover the focus and continue typing, but font change does not work. The font used is whatever the font used in the insertion point you clicked. At that time, the font shown in the font panel may not be the font you are typing. Before the fix, the focus was not returning to canvas no matter where you clicked.

**Comment by chadrolfs** [comment] 2015-09-14 18:42
Just hit this on Windows trying to access Typeface dropdown via tab:
![ice_screenshot_20150914-114355](https://cloud.githubusercontent.com/assets/8442631/9858475/b3cb9aec-5ad5-11e5-9e74-205d36fe5088.png)

**Comment by chadrolfs** [comment] 2015-09-14 22:59
Ian has a branch that addresses this ^^

**Comment by chadrolfs** [comment] 2015-09-15 18:00
This is better but not totally fixed.  Removing MAX from label since there are no longer console errors or stuck in a bad state.  

Once you are in a state where you're editing a Type attribute, Esc will not commit the text until you click on canvas.  There are definite focus issues going on an this may not be related to Type.  

select the Rect tool
drag out a shape
click on color picker and assign a color, hit Esc a bunch of times
then hit any of the shortcuts for tools (v for example), nothing happens

**Comment by ktaki** [comment] 2015-10-02 00:22
The core bug has been Closed/Fixed. Verified mainline builds on Mac and Windows.

**Closed by ktaki** 2015-10-02 00:22 UTC
Labels: High Pri, PS core, PS core hasWatson, Type
