### ISSUE TITLE
Dragging layers in layer panel draws layer in upper left of app window

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1577] opened 2015-06-15 20:03 UTC
https://www.dropbox.com/s/1bdsp32wnz30z6p/LayersDrag.mov?dl=0

**Comment by iwehrman** [comment] 2015-06-26 22:21
Not addressed by #1625.

**Comment by designedbyscience** [comment] 2015-07-07 19:32
This should also be fixed by  #1673

**Comment by chadrolfs** [comment] 2015-07-07 23:14
I can still repro.

**Comment by designedbyscience** [comment] 2015-07-08 14:13
@chadrolfs I can't reproduce this, is there anything in particular that seems to trigger it?

**Comment by designedbyscience** [comment] 2015-07-08 19:11
Okay, this is related to the fact that the initial positions (state.startX and state.startY) are only applied when the layer is clicked on. If you select a bunch of layers with shift, you should be able to replicate this

**Comment by chadrolfs** [comment] 2015-07-09 00:22
Yep, you got it.  If you select more that one layer, you'll see this.

**Comment by iwehrman** [comment] 2015-07-09 19:04
Addressed by #1700. FBNC to @chadrolfs.

**Comment by chadrolfs** [comment] 2015-07-09 21:15
doh!  Still there.  Try these steps.  
New default doc (AB)
Select Rect tool and drag out 3 shapes (Rect 3 should be at top of AB stack and selected)
Hold down Shift and select Rect 1 (all 3 shape layers selected), then drag down

**Comment by designedbyscience** [comment] 2015-07-09 21:21
Hmm... I don't see it when I try these steps. @iwehrman do the repro steps work for you?

**Comment by chadrolfs** [comment] 2015-07-09 21:22
something was off with my environment, i refreshed everything and now CNR

**Closed** 2015-07-09 21:23 UTC
Labels: High Pri, UI
