### ISSUE TITLE
Radius shows for non-rect shapes

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3530] opened 2016-01-14 19:01 UTC
create a shape with either the pen or ellipse tool

Result: Radius field and slider appear in Appearance panel 

this is a regression based on 16.1.2 functionality

**Comment by iwehrman** [comment] 2016-01-18 21:58
Is this a dupe of #3444?

**Comment by chadrolfs** [comment] 2016-01-19 17:00
root cause for both bugs maybe the same, but in testing 16.1.2, this bug does **not** occur but 3444 **does**.  In current jenkins/master both bugs occur.  

Another distinction is that in this bug, the controls show but are inactive (you can't enter a Radius or move the slider).  In 3444 after you rotate the rect, the controls are still active but don't do anything.

**Comment by iwehrman** [comment] 2016-01-21 20:07
FBNC to @chadrolfs.

**Closed** 2016-01-21 23:07 UTC
Labels: Fixed but not closed, Medium Pri, Polish, REGRESSION
