### ISSUE TITLE
Smart guides show over our paneling

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2356] opened 2015-09-08 18:38 UTC
Zoom in so that there are parts of your document behind our UI.

Select a shape and then hold down CMD (or do any shortcut with the CMD key) - all smart guides show up above our paneling

EXPECT: Smart Guides to only show on canvas

<img width="1335" alt="screen shot 2015-09-08 at 11 35 17 am" src="https://cloud.githubusercontent.com/assets/7904855/9743985/1a3815ec-561e-11e5-8d96-cac108e55b95.png">

**Comment by iwehrman** [comment] 2015-09-08 18:40
Dupe of #1632.

**Closed by iwehrman** 2015-09-08 18:40 UTC
