### ISSUE TITLE
If fill is not visible, alpha of stroke appears to be 100% on canvas

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2077] opened 2015-08-17 21:20 UTC
Could be the same root cause as #2076, but reporting this anyway.
Draw a rectangle. Add a stroke and set the alpha to be 20%.
Click on Toggle Fill icon to make the fill invisible.
RESULT: Stroke will be drawn as the alpha value 100% on canvas.

**Comment by volfied** [comment] 2015-08-17 22:29
Dupe of https://github.com/adobe-photoshop/spaces-design/issues/526

**Closed by volfied** 2015-08-17 22:29 UTC
Labels: Fix in progress
