### ISSUE TITLE
Switching tools while creating text removes text

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#1949] opened 2015-08-07 16:26 UTC
- Create a text layer
- type a few characters
- change tools in the toolbar
- text layer is removed

expected: text should remain, be selected as as layer, and the new tool should be selected

**Comment by chadrolfs** [comment] 2015-08-07 16:35
Glad you noticed this and it bugged you enough to write up an issue.  This has been around for a while.  This is a dupe of #1691

**Closed by chadrolfs** 2015-08-07 16:35 UTC
Labels: duplicate, Type
