### ISSUE TITLE
Create New Library text input does not immediately have focus 

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2540] opened 2015-09-18 22:18 UTC
When you select "Create New Library" from the Libraries `Datalist`, focus should be transferred to the text input so that you can just start typing the new library name. See #2536 for details, which may well have contributed to the bug?

**Comment by chadrolfs** [comment] 2015-09-21 16:17
Dupe of #2197 ?

**Closed** 2015-09-24 20:15 UTC
Labels: CC Libraries
