### ISSUE TITLE
Mixed Appearances Panel should enable it's controls for valid layers in selection

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#3465] opened 2016-01-05 22:34 UTC
Right now, if you have two shapes and a text layer selected, Radius input will be disabled, because we disable all controls on mixed layer types. The entire Mixed Appearance panel should be enabled and allow changes but change only the right layers.

**Comment by chadrolfs** [comment] 2016-02-03 19:05
![screen shot 2016-02-03 at 11 04 47 am](https://cloud.githubusercontent.com/assets/8442631/12793552/1063095c-ca66-11e5-9b5b-bd4b46528a29.png)

**Comment by chadrolfs** [comment] 2016-02-16 18:34
This is a dupe of #3147

**Closed by chadrolfs** 2016-02-16 18:34 UTC
Labels: Duplicate, Fix in progress, High Pri, Polish, REGRESSION
